---
  - hosts: all
    tasks:
      - name: Stop service httpd if started
        service:
          name: httpd
          state: stopped
      - name: Deinstall httpd package
        yum:
          name: httpd
          state: absent
      - name: Print message
        ansible.builtin.debug:
          msg: Deinstall package done! 
      
