--- 
  - hosts: awx
    tasks:
      - name: Install httpd package
        yum:
          name: httpd
          state: present
      - name: Start service httpd, if stopped
        service:
          name: httpd
          state: started
      - name: Print message
        ansible.builtin.debug:
          msg: install package done!    
