---
- name: Execute the command in remote shell; stdout goes to the specified file on the remote
  hosts: all
  tasks:
     - name: Execute the script
       ansible.builtin.shell: /home/scripts/runme.sh >> /home/scripts/runme.log
